// Conneqt News — bilingual static site generator
// Produces English (root) + Arabic (/ar) versions with RTL handling,
// plus /api/articles-en.json and /api/articles-ar.json feeds for any
// downstream consumer (Base44, custom site, etc).

const fs = require("fs");
const path = require("path");
const articlesEN = require("../articles/articles.js");
const articlesAR = require("../articles/articles-ar.js");

const SITE = {
  url: "https://ainewsksa.com",
  name: "AI News KSA",
  nameAR: "أخبار الذكاء الاصطناعي",
  tagline: "AI for marketing & growth in MENA — generated by an autonomous engine",
  taglineAR: "الذكاء الاصطناعي للتسويق والنمو في الشرق الأوسط — مُولَّد بواسطة محرك مستقل",
  description: "Industry analysis on AI content engines, programmatic SEO, blockchain ad networks, and lifecycle marketing — produced and published autonomously for the MENA market.",
  descriptionAR: "تحليل قطاعي عن محركات المحتوى بالذكاء الاصطناعي، SEO البرمجي، شبكات إعلانات البلوكشين، وتسويق دورة الحياة — يُنتَج ويُنشَر تلقائياً لسوق الشرق الأوسط وشمال أفريقيا.",
  twitter: "@conneqtmeAI",
};

const PUBLIC = path.resolve(__dirname, "../public");
const ARTICLES_EN_DIR = path.join(PUBLIC, "articles");
const AR_DIR = path.join(PUBLIC, "ar");
const ARTICLES_AR_DIR = path.join(AR_DIR, "articles");
const API_DIR = path.join(PUBLIC, "api");

// ============ STYLES ============
const baseCSS = `
:root {
  --bg: #0A0A0A;
  --card: #1A1A1A;
  --ink: #F2F2F2;
  --muted: #A8A8A8;
  --faint: #606060;
  --accent: #2BFF52;
  --rule: #2A2A2A;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { background: var(--bg); color: var(--ink); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif; line-height: 1.55; -webkit-font-smoothing: antialiased; }
html[lang="ar"] { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI Arabic", "Tahoma", "Geeza Pro", "Noto Sans Arabic", Arial, sans-serif; }
body { min-height: 100vh; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

.wrap { max-width: 1200px; margin: 0 auto; padding: 0 24px; }
.wrap-narrow { max-width: 760px; margin: 0 auto; padding: 0 24px; }

header { border-bottom: 1px solid var(--rule); padding: 22px 0; position: sticky; top: 0; background: rgba(10,10,10,0.92); backdrop-filter: blur(8px); z-index: 10; }
.header-inner { display: flex; align-items: center; justify-content: space-between; }
.logo { font-weight: 800; font-size: 20px; letter-spacing: 0.5px; color: var(--ink); }
.logo span { color: var(--accent); }
.nav { display: flex; align-items: center; }
.nav a { color: var(--muted); margin-inline-start: 28px; font-size: 14px; letter-spacing: 0.5px; text-transform: uppercase; font-weight: 600; }
.nav a:hover { color: var(--ink); text-decoration: none; }
.nav .lang { border: 1px solid var(--rule); padding: 6px 12px; border-radius: 4px; color: var(--accent); font-size: 12px; letter-spacing: 1px; }
.nav .lang:hover { background: var(--accent); color: #000; }
html[lang="ar"] .nav a { letter-spacing: 0; text-transform: none; font-size: 15px; }

.hero { padding: 80px 0 48px; border-bottom: 1px solid var(--rule); }
.hero h1 { font-size: clamp(34px, 5vw, 56px); font-weight: 800; line-height: 1.05; letter-spacing: -0.02em; margin-bottom: 20px; }
html[lang="ar"] .hero h1 { letter-spacing: 0; line-height: 1.25; }
.hero h1 .accent { color: var(--accent); }
.hero p { font-size: 18px; color: var(--muted); max-width: 720px; line-height: 1.6; }
.hero .meta { margin-top: 24px; font-size: 12px; color: var(--faint); letter-spacing: 1.5px; text-transform: uppercase; }
html[lang="ar"] .hero .meta { letter-spacing: 0; text-transform: none; font-size: 14px; }
.hero .meta .live::before { content: ""; display: inline-block; width: 8px; height: 8px; background: var(--accent); border-radius: 50%; margin-inline-end: 8px; vertical-align: middle; box-shadow: 0 0 8px var(--accent); }

.list { padding: 40px 0 56px; }
.list h2 { font-size: 13px; letter-spacing: 2px; text-transform: uppercase; color: var(--accent); margin-bottom: 20px; font-weight: 700; }
html[lang="ar"] .list h2 { letter-spacing: 0; text-transform: none; font-size: 16px; }

/* Tag filter bar */
.tag-bar { display: flex; flex-wrap: wrap; gap: 8px; padding: 0 0 32px; border-bottom: 1px solid var(--rule); margin-bottom: 32px; }
.tag-chip { background: var(--card); border: 1px solid var(--rule); color: var(--ink); padding: 7px 14px; border-radius: 22px; font-size: 13px; font-weight: 500; cursor: pointer; display: inline-flex; align-items: center; gap: 6px; transition: all 0.15s ease; font-family: inherit; line-height: 1; }
.tag-chip:hover { border-color: var(--accent); color: var(--accent); }
.tag-chip.active { background: var(--accent); color: #000; border-color: var(--accent); font-weight: 600; }
.tag-chip .tag-icon { font-size: 14px; line-height: 1; }
html[lang="ar"] .tag-chip { font-size: 14px; }
.no-results { color: var(--muted); font-size: 16px; padding: 40px 0; text-align: center; display: none; }
.no-results.show { display: block; }
.article-card { display: block; padding: 28px 0; border-bottom: 1px solid var(--rule); transition: padding 0.2s; }
.article-card:hover { text-decoration: none; }
.article-card:hover .article-title { color: var(--accent); }
.article-card .tags { font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; color: var(--faint); margin-bottom: 8px; }
html[lang="ar"] .article-card .tags { letter-spacing: 0; text-transform: none; font-size: 13px; }
.article-card .tags span { color: var(--accent); margin-inline-end: 12px; }
.article-title { font-size: 26px; font-weight: 700; color: var(--ink); margin-bottom: 12px; line-height: 1.25; transition: color 0.2s; }
html[lang="ar"] .article-title { line-height: 1.4; }
.article-card .dek { font-size: 16px; color: var(--muted); line-height: 1.6; max-width: 760px; }
.article-card .footer-meta { margin-top: 12px; font-size: 12px; color: var(--faint); }

.article-hero { padding: 56px 0 40px; border-bottom: 1px solid var(--rule); }
.article-hero .tags { font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; color: var(--accent); font-weight: 700; margin-bottom: 16px; }
html[lang="ar"] .article-hero .tags { letter-spacing: 0; text-transform: none; font-size: 14px; }
.article-hero h1 { font-size: clamp(28px, 4vw, 44px); font-weight: 800; line-height: 1.15; letter-spacing: -0.015em; margin-bottom: 20px; }
html[lang="ar"] .article-hero h1 { letter-spacing: 0; line-height: 1.4; }
.article-hero .dek { font-size: 19px; color: var(--muted); line-height: 1.55; }
.article-hero .meta { margin-top: 28px; font-size: 12px; color: var(--faint); letter-spacing: 1.5px; text-transform: uppercase; }
html[lang="ar"] .article-hero .meta { letter-spacing: 0; text-transform: none; font-size: 14px; }
.article-hero .meta .sep { margin: 0 12px; color: var(--rule); }

.article-body { padding: 48px 0 64px; }
.article-body p { font-size: 17px; line-height: 1.75; color: var(--ink); margin-bottom: 22px; }
html[lang="ar"] .article-body p { font-size: 18px; line-height: 1.9; }
.article-body h2 { font-size: 24px; font-weight: 700; color: var(--ink); margin: 40px 0 16px; line-height: 1.3; }
html[lang="ar"] .article-body h2 { line-height: 1.5; }
.article-body strong { color: var(--ink); font-weight: 700; }
.article-body em { color: var(--muted); }

.article-footer { padding: 40px 0 64px; border-top: 1px solid var(--rule); margin-top: 32px; }
.article-footer .label { font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; color: var(--accent); font-weight: 700; margin-bottom: 16px; }
html[lang="ar"] .article-footer .label { letter-spacing: 0; text-transform: none; font-size: 14px; }

.engine-block { background: var(--card); border-inline-start: 3px solid var(--accent); padding: 24px 28px; margin: 40px 0; border-radius: 0 4px 4px 0; }
html[lang="ar"] .engine-block { border-radius: 4px 0 0 4px; }
.engine-block .label { font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; color: var(--accent); font-weight: 700; margin-bottom: 8px; }
html[lang="ar"] .engine-block .label { letter-spacing: 0; text-transform: none; font-size: 14px; }
.engine-block p { font-size: 15px; color: var(--muted); line-height: 1.6; margin: 0; }

.about-hero { padding: 80px 0 32px; }
.about-hero h1 { font-size: clamp(32px, 4.5vw, 52px); font-weight: 800; line-height: 1.1; letter-spacing: -0.02em; margin-bottom: 20px; }
html[lang="ar"] .about-hero h1 { letter-spacing: 0; line-height: 1.3; }
.about-hero h1 .accent { color: var(--accent); }
.layers { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 16px; padding: 32px 0 64px; }
.layer { background: var(--card); border: 1px solid var(--rule); padding: 22px; border-radius: 6px; }
.layer .num { font-size: 11px; letter-spacing: 1.5px; text-transform: uppercase; color: var(--accent); font-weight: 700; margin-bottom: 8px; }
html[lang="ar"] .layer .num { letter-spacing: 0; text-transform: none; font-size: 13px; }
.layer h3 { font-size: 17px; font-weight: 700; color: var(--ink); margin-bottom: 8px; }
.layer p { font-size: 14px; color: var(--muted); line-height: 1.55; }

footer { border-top: 1px solid var(--rule); padding: 40px 0 56px; margin-top: 64px; }
.footer-inner { display: flex; flex-wrap: wrap; gap: 40px; align-items: flex-start; justify-content: space-between; }
.footer-brand { font-weight: 800; font-size: 16px; color: var(--ink); margin-bottom: 8px; }
.footer-brand span { color: var(--accent); }
.footer-meta { font-size: 13px; color: var(--faint); }
.footer-links { display: flex; gap: 24px; flex-wrap: wrap; }
.footer-links a { color: var(--muted); font-size: 13px; }

@media (max-width: 640px) {
  .nav a:not(.lang) { display: none; }
  .article-card { padding: 22px 0; }
  .article-title { font-size: 22px; }
  .hero { padding: 48px 0 32px; }
  .article-body { padding: 32px 0 40px; }
}
`;

// ============ COPY TABLE ============
const COPY = {
  en: {
    home: "Home",
    engine: "The Engine",
    conneqt: "Conneqtme.com",
    lang: "العربية",
    langPath: "/ar/",
    heroLine1: "AI for marketing.",
    heroLine2Pre: "Generated by an ",
    heroLine2Accent: "engine,",
    heroLine2Post: " not a team.",
    heroDek: "Industry analysis on AI content engines, programmatic SEO, blockchain ad networks, lifecycle automation, and the production AI stack reshaping marketing in 2026.",
    updated: "Updated automatically · Last build",
    latest: "Latest analysis",
    related: "Related",
    aboutHeroPre: "This site runs on an engine ",
    aboutHeroAccent: "built by Conneqt.",
    aboutHeroDek: "AI News KSA is a live deployment of the AI content engine that Conneqt ships for sportsbook, crypto, and digital-first operators across MENA. Every article on this site is generated, fact-checked, and published autonomously through the eight-layer pipeline below.",
    aboutHeroSub: "Editorial focus: AI for marketing and growth. Refresh cadence: continuous, with new articles published as new sources flow through the ingestion layer.",
    pipeline: "The pipeline",
    whyTitle: "Why we run our own engine on our own content",
    whyBody: "Most AI content vendors sell the product without using it. Conneqt News exists because we believed the strongest demonstration of the engine is to run it autonomously on our own publication and let the work speak. Every article you read here is produced by the same architecture we deploy for client pilots — same cost economics, same fact-check layer, same publishing latency.",
    operatorsTitle: "For operators evaluating the engine",
    operatorsBody: "If you're running a sportsbook, crypto project, or digital-first operator and the content velocity ceiling is becoming visible — Conneqt deploys vertical-tuned content engines on a 6-week pilot timeline against fixed fees. The engine in your stack will look architecturally identical to the one running this publication, configured for your data feeds, your voice, your markets.",
    getInTouch: "Get in touch",
    howThisWorks: "How this works",
    sitemap: "Sitemap",
    siteFooterTagline: "AI news for the MENA market. Powered by Conneqt — AI & Automation.",
    howArticleProduced: "How this article was produced",
    howArticleProducedBody: "This piece was generated by an autonomous AI content engine from a brief assembled out of RSS-tracked AI marketing feeds, fact-checked against source material via retrieval-augmented generation, and published without human intervention. Engine architecture by Conneqt.",
    fullPipeline: "See the full pipeline",
  },
  ar: {
    home: "الرئيسية",
    engine: "المحرك",
    conneqt: "Conneqtme.com",
    lang: "English",
    langPath: "/",
    heroLine1: "الذكاء الاصطناعي للتسويق.",
    heroLine2Pre: "مُولَّد بواسطة ",
    heroLine2Accent: "محرك،",
    heroLine2Post: " وليس فريقاً.",
    heroDek: "تحليل قطاعي عن محركات المحتوى بالذكاء الاصطناعي، SEO البرمجي، شبكات إعلانات البلوكشين، أتمتة دورة الحياة، وستاك الذكاء الاصطناعي الإنتاجي الذي يُعيد تشكيل التسويق في 2026.",
    updated: "يُحدَّث تلقائياً · آخر بناء",
    latest: "أحدث التحليلات",
    related: "ذات صلة",
    aboutHeroPre: "هذا الموقع يعمل على محرك ",
    aboutHeroAccent: "بناه كونيكت.",
    aboutHeroDek: "أخبار الذكاء الاصطناعي KSA هي نشر حي لمحرك المحتوى بالذكاء الاصطناعي الذي تُسلّمه كونيكت لشركات الرهان الرياضي والكريبتو ومُشغّلي الأعمال الرقمية عبر منطقة الشرق الأوسط وشمال أفريقيا. كل مقال على هذا الموقع يُولَّد، يُتحقق منه، ويُنشَر تلقائياً عبر الطبقات الثماني أدناه.",
    aboutHeroSub: "التركيز التحريري: الذكاء الاصطناعي للتسويق والنمو. وتيرة التحديث: مستمرة، مع نشر مقالات جديدة كلما تدفّقت مصادر جديدة عبر طبقة الاستيعاب.",
    pipeline: "خط الأنابيب",
    whyTitle: "لماذا نُشغّل محركنا الخاص على محتوانا الخاص",
    whyBody: "معظم بائعي محتوى الذكاء الاصطناعي يبيعون المنتج دون استخدامه. أخبار كونيكت موجودة لأننا اعتقدنا أن أقوى عرض للمحرك هو تشغيله تلقائياً على نشرتنا الخاصة وترك العمل يتكلّم. كل مقال تقرأه هنا يُنتَج بواسطة نفس البنية التي ننشرها لبرامج العملاء التجريبية — نفس اقتصاديات التكلفة، نفس طبقة التحقق من الحقائق، نفس زمن انتقال النشر.",
    operatorsTitle: "للمُشغّلين الذين يُقيّمون المحرك",
    operatorsBody: "إذا كنت تُدير شركة رهان رياضي، أو مشروع كريبتو، أو عمليات رقمية متقدّمة، وأصبح سقف سرعة المحتوى مرئياً — كونيكت تنشر محركات محتوى مُصمّمة قطاعياً على جدول زمني تجريبي مدته 6 أسابيع برسوم ثابتة. المحرك في ستاكك سيبدو متطابقاً معمارياً مع الذي يُشغّل هذه النشرة، مُهيّأ لتغذية بياناتك، صوتك، أسواقك.",
    getInTouch: "تواصل معنا",
    howThisWorks: "كيف يعمل هذا",
    sitemap: "خريطة الموقع",
    siteFooterTagline: "أخبار الذكاء الاصطناعي لسوق الشرق الأوسط وشمال أفريقيا. مدعوم من كونيكت — الذكاء الاصطناعي والأتمتة.",
    howArticleProduced: "كيف أُنتج هذا المقال",
    howArticleProducedBody: "أُنتج هذا المقال بواسطة محرك مستقل للمحتوى بالذكاء الاصطناعي من ملخص مُجمَّع من تغذيات RSS للذكاء الاصطناعي والتسويق، تم التحقق منه مقابل المادة المصدرية عبر التوليد المعزز بالاسترجاع، ونُشر دون تدخل بشري. هندسة المحرك بواسطة كونيكت.",
    fullPipeline: "اطّلع على خط الأنابيب الكامل",
  },
};

const LAYERS_EN = [
  { num: "01", title: "Data ingestion", body: "RSS feeds from TechCrunch AI, The Verge AI, Anthropic, OpenAI, Google AI blog, ArXiv. Polled every 6 hours for new sources." },
  { num: "02", title: "Brief generation", body: "Each tracked story is assembled into a structured content brief — angle, supporting facts, target audience, target length, voice constraints." },
  { num: "03", title: "Voice & guardrails", body: "Versioned system prompts encode the editorial voice (analytical, industry-focused, no marketing fluff) and topic boundaries." },
  { num: "04", title: "Generation", body: "Anthropic Claude Sonnet 4.6 generates the article body from the brief. Long-form, on-tone, with internal structure." },
  { num: "05", title: "Fact-check (RAG)", body: "Retrieval-augmented verification against source material catches hallucinated stats, names, dates, or company references before publish." },
  { num: "06", title: "SEO formatting", body: "schema.org Article markup, internal linking to related pieces, hreflang tags, sitemap regeneration. Programmatic SEO at scale." },
  { num: "07", title: "Publish", body: "Static HTML pushed via git commit. New articles live in under 60 seconds. CDN-distributed globally." },
  { num: "08", title: "Analytics feedback", body: "Engagement signals (read time, scroll depth, return visits) feed back to the brief generator to evolve topic selection." }
];

const LAYERS_AR = [
  { num: "٠١", title: "استيعاب البيانات", body: "تغذيات RSS من TechCrunch AI، The Verge AI، Anthropic، OpenAI، مدونة Google AI، و ArXiv. تُستطلَع كل 6 ساعات لمصادر جديدة." },
  { num: "٠٢", title: "توليد الملخصات", body: "كل قصة متتبَّعة تُجمَّع في ملخص محتوى منظم — الزاوية، الحقائق الداعمة، الجمهور المستهدف، الطول المستهدف، قيود الصوت." },
  { num: "٠٣", title: "الصوت والحواجز", body: "موجِّهات نظامية ذات إصدارات تُشفّر الصوت التحريري (تحليلي، مُوجّه قطاعياً، بلا حشو تسويقي) وحدود الموضوعات." },
  { num: "٠٤", title: "التوليد", body: "Anthropic Claude Sonnet 4.6 يُولّد متن المقال من الملخص. طويل، متّسق النبرة، ببنية داخلية." },
  { num: "٠٥", title: "التحقق من الحقائق (RAG)", body: "تحقق معزز بالاسترجاع مقابل المادة المصدرية يلتقط الإحصاءات والأسماء والتواريخ والمراجع المُهلوسة قبل النشر." },
  { num: "٠٦", title: "تنسيق SEO", body: "علامات schema.org للمقال، ربط داخلي مع القطع ذات الصلة، علامات hreflang، إعادة توليد خريطة الموقع. SEO برمجي على نطاق واسع." },
  { num: "٠٧", title: "النشر", body: "HTML ثابت يُدفع عبر git commit. مقالات جديدة تعيش في أقل من 60 ثانية. موزّعة عبر CDN عالمياً." },
  { num: "٠٨", title: "التغذية الراجعة للتحليلات", body: "إشارات التفاعل (وقت القراءة، عمق التمرير، الزيارات المتكررة) تُغذّي مُولّد الملخصات لتطوير اختيار الموضوعات." }
];

// ============ TEMPLATES ============
function head(lang, title, description, ogTitle, ogDesc, canonicalPath, articleSchema) {
  const url = SITE.url + canonicalPath;
  const dir = lang === "ar" ? "rtl" : "ltr";
  const c = COPY[lang];
  const homeHref = lang === "ar" ? "/ar/" : "/";
  const aboutHref = lang === "ar" ? "/ar/about.html" : "/about.html";
  return `<!doctype html>
<html lang="${lang}" dir="${dir}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
  <meta name="description" content="${description}">
  <link rel="canonical" href="${url}">
  <link rel="alternate" hreflang="en" href="${SITE.url}${canonicalPath.startsWith("/ar") ? canonicalPath.replace(/^\/ar/, "") : canonicalPath}">
  <link rel="alternate" hreflang="ar" href="${SITE.url}${canonicalPath.startsWith("/ar") ? canonicalPath : "/ar" + canonicalPath}">
  <link rel="alternate" hreflang="x-default" href="${SITE.url}/">
  <meta property="og:title" content="${ogTitle || title}">
  <meta property="og:description" content="${ogDesc || description}">
  <meta property="og:type" content="${articleSchema ? "article" : "website"}">
  <meta property="og:url" content="${url}">
  <meta property="og:locale" content="${lang === "ar" ? "ar_SA" : "en_US"}">
  <meta property="og:site_name" content="${SITE.name}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="${SITE.twitter}">
  <meta name="twitter:title" content="${ogTitle || title}">
  <meta name="twitter:description" content="${ogDesc || description}">
  <meta name="theme-color" content="#0A0A0A">
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Crect width='100' height='100' fill='%230A0A0A'/%3E%3Ctext x='50' y='62' font-size='52' font-weight='800' text-anchor='middle' fill='%232BFF52' font-family='-apple-system,sans-serif'%3EC.%3C/text%3E%3C/svg%3E">
  <style>${baseCSS}</style>
  ${articleSchema || ""}
</head>
<body>
  <header>
    <div class="wrap header-inner">
      <a href="${homeHref}" class="logo">AI NEWS<span>.</span> KSA</a>
      <nav class="nav">
        <a href="${homeHref}">${c.home}</a>
        <a href="${aboutHref}">${c.engine}</a>
        <a href="https://conneqtme.com" target="_blank" rel="noopener">${c.conneqt}</a>
        <a href="${c.langPath}" class="lang">${c.lang}</a>
      </nav>
    </div>
  </header>`;
}

function footer(lang) {
  const c = COPY[lang];
  const aboutHref = lang === "ar" ? "/ar/about.html" : "/about.html";
  return `
  <footer>
    <div class="wrap">
      <div class="footer-inner">
        <div>
          <div class="footer-brand">AI NEWS<span>.</span> KSA</div>
          <div class="footer-meta">${c.siteFooterTagline}</div>
        </div>
        <div class="footer-links">
          <a href="${aboutHref}">${c.howThisWorks}</a>
          <a href="/sitemap.xml">${c.sitemap}</a>
          <a href="https://conneqtme.com" target="_blank" rel="noopener">Conneqt</a>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>`;
}

// Tag → emoji icon mapping (works across both languages)
const TAG_ICONS = {
  // English tags
  "SEO": "🔍", "Programmatic content": "⚡", "Industry analysis": "📊",
  "Sportsbook": "🎯", "AI content": "🤖", "iGaming": "🎲",
  "Telegram": "💬", "Growth": "📈", "Restricted verticals": "🚧",
  "Crypto marketing": "₿", "Ad networks": "📣", "Web3": "🔗",
  "Localization": "🌍", "Multi-market": "🌐", "Content strategy": "📝",
  "RAG": "🔬", "Production AI": "⚙️", "Quality": "✓",
  "Ad creative": "🎨", "Agencies": "🏢", "Industry": "🏛",
  "Lifecycle": "👤", "CRM": "📇", "Personalization": "🎯",
  "Long-tail": "📏", "Marketing leadership": "👔", "Strategy": "♟",
  "AI": "🤖",
  // Arabic tags
  "محتوى برمجي": "⚡", "تحليل قطاعي": "📊",
  "رهان رياضي": "🎯", "ذكاء اصطناعي": "🤖",
  "تليغرام": "💬", "نمو": "📈", "قطاعات مقيّدة": "🚧",
  "تسويق الكريبتو": "₿", "شبكات إعلانية": "📣",
  "التوطين": "🌍", "متعدد الأسواق": "🌐", "استراتيجية محتوى": "📝",
  "الذكاء الاصطناعي الإنتاجي": "⚙️", "الجودة": "✓",
  "إبداع إعلاني": "🎨", "وكالات": "🏢", "صناعة": "🏛",
  "دورة الحياة": "👤", "التخصيص": "🎯",
  "ذيل طويل": "📏", "إنتاج الذكاء الاصطناعي": "⚙️",
  "قيادة التسويق": "👔", "استراتيجية": "♟",
};
function tagIcon(tag) { return TAG_ICONS[tag] || "📄"; }

function fmtDate(iso, lang) {
  const d = new Date(iso);
  if (lang === "ar") {
    return d.toLocaleDateString("ar-EG", { year: "numeric", month: "long", day: "numeric" });
  }
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

// ============ INDEX PAGE ============
function indexHTML(lang) {
  const articles = lang === "ar" ? articlesAR : articlesEN;
  const c = COPY[lang];
  const sorted = [...articles].sort((a, b) => b.date.localeCompare(a.date));
  const articlePath = lang === "ar" ? "/ar/articles/" : "/articles/";

  // Extract unique tags across all articles
  const allTags = [...new Set(sorted.flatMap(a => a.tags))];

  const allLabel = lang === "ar" ? "الكل" : "All";
  const noResultsLabel = lang === "ar" ? "لا توجد مقالات بهذا الوسم." : "No articles match this filter.";

  const tagChips = `
    <button class="tag-chip active" data-tag="all"><span class="tag-icon">🗂</span> ${allLabel}</button>
    ${allTags.map(t => `<button class="tag-chip" data-tag="${t.replace(/"/g, "&quot;")}"><span class="tag-icon">${tagIcon(t)}</span> ${t}</button>`).join("\n")}
  `;

  const cards = sorted.map(a => `
    <a class="article-card" data-tags="${a.tags.map(t => t.replace(/"/g, "&quot;")).join("|")}" href="${articlePath}${a.slug}.html">
      <div class="tags">${a.tags.map(t => `<span>${t}</span>`).join(" ")}</div>
      <div class="article-title">${a.title}</div>
      <div class="dek">${a.dek}</div>
      <div class="footer-meta">${fmtDate(a.date, lang)} · ${a.readTime}</div>
    </a>`).join("\n");

  const filterScript = `
    <script>
      (function () {
        const chips = document.querySelectorAll('.tag-chip');
        const cards = document.querySelectorAll('.article-card');
        const noResults = document.getElementById('no-results');
        chips.forEach(chip => {
          chip.addEventListener('click', () => {
            const tag = chip.getAttribute('data-tag');
            chips.forEach(c => c.classList.remove('active'));
            chip.classList.add('active');
            let visibleCount = 0;
            cards.forEach(card => {
              const cardTags = (card.getAttribute('data-tags') || '').split('|');
              if (tag === 'all' || cardTags.indexOf(tag) !== -1) {
                card.style.display = '';
                visibleCount++;
              } else {
                card.style.display = 'none';
              }
            });
            if (noResults) noResults.classList.toggle('show', visibleCount === 0);
          });
        });
      })();
    </script>
  `;

  return head(
    lang,
    `${SITE.name} — ${lang === "ar" ? SITE.taglineAR : SITE.tagline}`,
    lang === "ar" ? SITE.descriptionAR : SITE.description,
    SITE.name,
    lang === "ar" ? SITE.taglineAR : SITE.tagline,
    lang === "ar" ? "/ar/" : "/"
  ) + `
  <main>
    <section class="hero">
      <div class="wrap">
        <h1>${c.heroLine1}<br>${c.heroLine2Pre}<span class="accent">${c.heroLine2Accent}</span>${c.heroLine2Post}</h1>
        <p>${c.heroDek}</p>
        <div class="meta">
          <span class="live">${c.updated} ${fmtDate(sorted[0].date, lang)}</span>
        </div>
      </div>
    </section>
    <section class="list">
      <div class="wrap">
        <div class="tag-bar">
          ${tagChips}
        </div>
        <h2>${c.latest}</h2>
        ${cards}
        <div id="no-results" class="no-results">${noResultsLabel}</div>
      </div>
    </section>
    ${filterScript}
  </main>` + footer(lang);
}

// ============ ARTICLE PAGE ============
function articleHTML(a, lang) {
  const articles = lang === "ar" ? articlesAR : articlesEN;
  const c = COPY[lang];
  const articlePath = lang === "ar" ? "/ar/articles/" : "/articles/";
  const aboutHref = lang === "ar" ? "/ar/about.html" : "/about.html";
  const sorted = [...articles].sort((x, y) => y.date.localeCompare(x.date));
  const idx = sorted.findIndex(x => x.slug === a.slug);
  const related = sorted.filter((_, i) => i !== idx).slice(0, 3);

  const schema = `<script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": a.title,
    "description": a.dek,
    "datePublished": a.date,
    "dateModified": a.date,
    "inLanguage": lang === "ar" ? "ar" : "en",
    "author": { "@type": "Organization", "name": "Conneqt" },
    "publisher": {
      "@type": "Organization",
      "name": "Conneqt",
      "logo": { "@type": "ImageObject", "url": SITE.url + "/logo.png" }
    },
    "mainEntityOfPage": { "@type": "WebPage", "@id": `${SITE.url}${articlePath}${a.slug}.html` },
    "keywords": a.tags.join(", ")
  })}</script>`;

  return head(
    lang,
    `${a.title} — ${SITE.name}`,
    a.dek,
    a.title,
    a.dek,
    `${articlePath}${a.slug}.html`,
    schema
  ) + `
  <main>
    <article>
      <section class="article-hero">
        <div class="wrap-narrow">
          <div class="tags">${a.tags.join(" · ")}</div>
          <h1>${a.title}</h1>
          <div class="dek">${a.dek}</div>
          <div class="meta">${fmtDate(a.date, lang)}<span class="sep">·</span>${a.readTime}<span class="sep">·</span>Conneqt</div>
        </div>
      </section>
      <section class="article-body">
        <div class="wrap-narrow">
          ${a.body}
          <div class="engine-block">
            <div class="label">${c.howArticleProduced}</div>
            <p>${c.howArticleProducedBody} <a href="${aboutHref}" style="color: var(--accent);">${c.fullPipeline} →</a></p>
          </div>
        </div>
      </section>
      <section class="article-footer">
        <div class="wrap-narrow">
          <div class="label">${c.related}</div>
          ${related.map(r => `
            <a class="article-card" href="${articlePath}${r.slug}.html">
              <div class="tags">${r.tags.map(t => `<span>${t}</span>`).join(" ")}</div>
              <div class="article-title">${r.title}</div>
              <div class="dek">${r.dek}</div>
            </a>`).join("\n")}
        </div>
      </section>
    </article>
  </main>` + footer(lang);
}

// ============ ABOUT PAGE ============
function aboutHTML(lang) {
  const c = COPY[lang];
  const layers = lang === "ar" ? LAYERS_AR : LAYERS_EN;
  const aboutPath = lang === "ar" ? "/ar/about.html" : "/about.html";

  return head(
    lang,
    `${c.engine} — ${SITE.name}`,
    lang === "ar" ? "كيف تُنتَج وتُنشَر أخبار كونيكت تلقائياً." : "How Conneqt News is produced and published autonomously.",
    `${c.engine} — ${SITE.name}`,
    lang === "ar" ? "كيف تُنتَج وتُنشَر أخبار كونيكت تلقائياً." : "How Conneqt News is produced and published autonomously.",
    aboutPath
  ) + `
  <main>
    <section class="about-hero">
      <div class="wrap-narrow">
        <h1>${c.aboutHeroPre}<span class="accent">${c.aboutHeroAccent}</span></h1>
        <p style="font-size: 19px; color: var(--muted); line-height: 1.6; margin-bottom: 24px;">${c.aboutHeroDek}</p>
        <p style="font-size: 16px; color: var(--muted); line-height: 1.6;">${c.aboutHeroSub}</p>
      </div>
    </section>

    <section>
      <div class="wrap-narrow">
        <h2 style="font-size: 13px; letter-spacing: 2px; text-transform: uppercase; color: var(--accent); margin-bottom: 8px; font-weight: 700;">${c.pipeline}</h2>
        <div class="layers">
          ${layers.map(l => `
            <div class="layer">
              <div class="num">${l.num} — ${l.title.toUpperCase()}</div>
              <h3>${l.title}</h3>
              <p>${l.body}</p>
            </div>`).join("\n")}
        </div>
      </div>
    </section>

    <section style="padding: 0 0 80px;">
      <div class="wrap-narrow">
        <div class="engine-block">
          <div class="label">${c.whyTitle}</div>
          <p>${c.whyBody}</p>
        </div>

        <h2 style="font-size: 24px; font-weight: 700; margin: 48px 0 16px;">${c.operatorsTitle}</h2>
        <p style="font-size: 17px; line-height: 1.75; color: var(--ink); margin-bottom: 22px;">${c.operatorsBody}</p>
        <p style="font-size: 17px; line-height: 1.75; color: var(--ink); margin-bottom: 22px;"><a href="https://conneqtme.com" style="color: var(--accent); font-weight: 700;">${c.getInTouch} →</a></p>
      </div>
    </section>
  </main>` + footer(lang);
}

// ============ SITEMAP / ROBOTS ============
function sitemap() {
  const urls = [
    { loc: SITE.url + "/", changefreq: "daily", priority: "1.0" },
    { loc: SITE.url + "/about.html", changefreq: "monthly", priority: "0.6" },
    { loc: SITE.url + "/ar/", changefreq: "daily", priority: "1.0" },
    { loc: SITE.url + "/ar/about.html", changefreq: "monthly", priority: "0.6" },
    ...articlesEN.map(a => ({
      loc: `${SITE.url}/articles/${a.slug}.html`,
      lastmod: a.date,
      changefreq: "monthly",
      priority: "0.8"
    })),
    ...articlesAR.map(a => ({
      loc: `${SITE.url}/ar/articles/${a.slug}.html`,
      lastmod: a.date,
      changefreq: "monthly",
      priority: "0.8"
    }))
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>${u.lastmod ? `\n    <lastmod>${u.lastmod}</lastmod>` : ""}
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join("\n")}
</urlset>`;
}

const robots = `User-agent: *
Allow: /

Sitemap: ${SITE.url}/sitemap.xml
`;

// ============ JSON API FEEDS ============
function feedJSON(lang) {
  const articles = lang === "ar" ? articlesAR : articlesEN;
  const sorted = [...articles].sort((a, b) => b.date.localeCompare(a.date));
  return JSON.stringify({
    site: SITE.name,
    language: lang,
    generated_at: new Date().toISOString(),
    article_count: sorted.length,
    articles: sorted.map(a => ({
      slug: a.slug,
      title: a.title,
      dek: a.dek,
      date: a.date,
      tags: a.tags,
      read_time: a.readTime,
      url: `${SITE.url}${lang === "ar" ? "/ar" : ""}/articles/${a.slug}.html`,
      body_html: a.body,
    })),
  }, null, 2);
}

// ============ WRITE ============
function ensureDir(p) { if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true }); }
ensureDir(PUBLIC);
ensureDir(ARTICLES_EN_DIR);
ensureDir(AR_DIR);
ensureDir(ARTICLES_AR_DIR);
ensureDir(API_DIR);

// English (root)
fs.writeFileSync(path.join(PUBLIC, "index.html"), indexHTML("en"));
fs.writeFileSync(path.join(PUBLIC, "about.html"), aboutHTML("en"));
articlesEN.forEach(a => {
  fs.writeFileSync(path.join(ARTICLES_EN_DIR, a.slug + ".html"), articleHTML(a, "en"));
});

// Arabic (/ar)
fs.writeFileSync(path.join(AR_DIR, "index.html"), indexHTML("ar"));
fs.writeFileSync(path.join(AR_DIR, "about.html"), aboutHTML("ar"));
articlesAR.forEach(a => {
  fs.writeFileSync(path.join(ARTICLES_AR_DIR, a.slug + ".html"), articleHTML(a, "ar"));
});

// Sitemap + robots
fs.writeFileSync(path.join(PUBLIC, "sitemap.xml"), sitemap());
fs.writeFileSync(path.join(PUBLIC, "robots.txt"), robots);

// JSON feeds for downstream consumers (Base44, etc.)
fs.writeFileSync(path.join(API_DIR, "articles-en.json"), feedJSON("en"));
fs.writeFileSync(path.join(API_DIR, "articles-ar.json"), feedJSON("ar"));

console.log(`Generated bilingual site:`);
console.log(`  ${articlesEN.length} English articles + index + about`);
console.log(`  ${articlesAR.length} Arabic articles + index + about`);
console.log(`  API feeds: /api/articles-en.json, /api/articles-ar.json`);
console.log(`  Sitemap + robots`);
console.log(`Output: ${PUBLIC}`);
